# Generated by Django 5.2.11 on 2026-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='Available for Strategic Opportunities', max_length=100)),
                ('hero_greeting', models.CharField(default='I am Bhoj Raj Upadhayay', max_length=200)),
                ('hero_title', models.CharField(default='Expert IT Systems Architect.', max_length=200)),
                ('hero_description', models.TextField(default='Mastering the intersection of enterprise infrastructure and modern software engineering. Specializing in SAP Business One, Python/Django, and high-performance database management.')),
                ('about_me_text_1', models.TextField(default='I am a passionate Full Stack Developer and IT Systems Architect with extensive experience in Python, Django, and SAP Business One. I specialize in building highly scalable, secure, and user-friendly web applications that bridge the gap between complex enterprise infrastructure and modern software engineering.')),
                ('about_me_text_2', models.TextField(default="My approach combines technical excellence with strategic problem-solving. Whether it's architecting a robust database schema in SQL HANA or creating an engaging, glassmorphic frontend interface, my goal is always to deliver comprehensive software solutions that empower businesses to thrive in the digital age.")),
                ('footer_text', models.CharField(default='Bhoj Raj Upadhayay. Engineered for Excellence.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
