# Generated by Django 5.0.14 on 2026-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ibisap', 'IbiSAP ERP'), ('compliance', 'Compliance & CBS'), ('workspace', 'Dev & Setup'), ('events', 'Events & Leadership')], default='ibisap', max_length=50)),
                ('category_label', models.CharField(default='IbiSAP ERP', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('static_image_path', models.CharField(blank=True, help_text='Fallback static path e.g. gallery/ibisap-dashboard.png', max_length=255, null=True)),
                ('caption', models.TextField()),
                ('tags', models.CharField(default='Django, ERP, Cloud', help_text='Comma separated tags', max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IbiSAPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('badge', models.CharField(default='Core Module', max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-cubes', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ibisap/modules/')),
                ('static_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enterprise_ready', models.BooleanField(default=True)),
                ('is_retail_ready', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='hero_description',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(blank=True, default='General Inquiry', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='date_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_me_lead',
            field=models.TextField(default='I am an IT Professional at a Nepal Rastra Bank (NRB)–regulated microfinance institution, an MBA candidate at Far Western University, and the Founder of Chill Tech.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_me_text_3',
            field=models.TextField(default="Seeing Nepali SMEs and regulated institutions priced out of exorbitant SAP Business One licensing fees, I founded Chill Tech to engineer IbiSAP — a modern, cost-effective, and NRB/CBMS-compliant ERP built specifically for Nepal's financial and business ecosystem."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_address',
            field=models.EmailField(default='bhojrajupadhayay2001@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/bhojrajupadhayay'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_subheadline',
            field=models.TextField(default="Leveraging hands-on Core Banking (CBS), NRB IT compliance, and SAP Business One experience at a regulated microfinance institution to engineer IbiSAP — Nepal's compliant, accessible enterprise ERP."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ibisap_live_url',
            field=models.URLField(blank=True, default='https://ibisap.rajabhoj.com.np'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/in/bhojrajupadhayay'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='location',
            field=models.CharField(default='Kathmandu / Kailali, Nepal', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.CharField(default='+977 (Available upon request)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='prakriti_prabhav_url',
            field=models.URLField(blank=True, default='https://prakritiprabhav.com'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_me_text_1',
            field=models.TextField(default='In my day-to-day role, I manage high-stakes Core Banking System (CBS) operations, enforce strict NRB IT security directives, architect Disaster Recovery Plans (DRP), and supervise mission-critical enterprise systems.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_me_text_2',
            field=models.TextField(default='My technical foundation spans hands-on SAP Business One implementation, SQL HANA database administration, Linux server infrastructure, and full-stack Python/Django engineering.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.CharField(default='Rajabhoj Upadhayay. Engineered for Enterprise Trust, Compliance & Scalability.', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_badge_text',
            field=models.CharField(default='Regulated MFI IT Systems • Founder, Chill Tech', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_greeting',
            field=models.CharField(default='Rajabhoj — IT Professional', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='ERP Builder | Founder, Chill Tech', max_length=200),
        ),
    ]
