# Generated by Django 6.1 on 2026-08-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0004_galleryitem_ibisapmodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact Phone / WhatsApp Number', max_length=50, null=True),
        ),
    ]
