# Generated by Django 6.1 on 2026-08-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0005_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='brand_name',
            field=models.CharField(default='BHOJ RAJ', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_1_desc',
            field=models.TextField(default='Deep expertise in high-concurrency ledger operations, Maker-Checker RBAC authorization, and regulatory compliance under Nepal Rastra Bank guidelines.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_1_title',
            field=models.CharField(default='Core Banking & CBS Systems', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_2_desc',
            field=models.TextField(default='Crafting scalable web backends, RESTful microservices, asynchronous task queues, and resilient financial transaction pipelines.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_2_title',
            field=models.CharField(default='Python & Django Architecture', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_3_desc',
            field=models.TextField(default="Database optimization, row-level locking consistency, and architectural design of IbiSAP — Nepal's compliant ERP alternative."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_3_title',
            field=models.CharField(default='SAP B1 & SQL HANA Ecosystem', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_4_desc',
            field=models.TextField(default='Weaving evocative verses in Nepali & English, contemplating human existence, philosophy, and the quiet harmony between technology and soul.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar_4_title',
            field=models.CharField(default='Poetic & Literary Expression', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_1_number',
            field=models.CharField(default='5+', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_1_sub',
            field=models.CharField(default='Enterprise IT & Web Systems', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_1_title',
            field=models.CharField(default='Years Architecture', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_2_number',
            field=models.CharField(default='100%', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_2_sub',
            field=models.CharField(default='Audit Trails & Disaster Recovery', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_2_title',
            field=models.CharField(default='NRB Compliance', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_3_number',
            field=models.CharField(default='15+', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_3_sub',
            field=models.CharField(default='ERP, POS, CBMS & Banking APIs', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_3_title',
            field=models.CharField(default='Enterprise Modules', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_4_number',
            field=models.CharField(default='50k+', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_4_sub',
            field=models.CharField(default='Clean, Resilient Microservices', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat_4_title',
            field=models.CharField(default='Lines of Code', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_number',
            field=models.CharField(default='+977 9848485292', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/9779848485292'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_me_lead',
            field=models.TextField(default='I am an IT Systems Architect, Full-Stack Engineer, and Creative Writer based in Nepal.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_me_text_1',
            field=models.TextField(default='In my professional practice, I architect and manage high-stakes Core Banking System (CBS) operations, enforce strict NRB IT security directives, design Disaster Recovery Plans (DRP), and supervise mission-critical enterprise systems.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_me_text_2',
            field=models.TextField(default='My technical foundation spans hands-on SAP Business One implementation, SQL HANA / PostgreSQL database administration, Linux server infrastructure, and full-stack Python/Django engineering.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_me_text_3',
            field=models.TextField(default="Beyond engineering determinism, I express life's reflective dimensions through poetry in Nepali and English, capturing philosophical depth and spiritual resonance."),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.CharField(default='Bhoj Raj Upadhayay. Engineered with Precision & Soul.', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_badge_text',
            field=models.CharField(default='IT Systems Architect • Full-Stack Engineer • Poet', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_greeting',
            field=models.CharField(default='I am Bhoj Raj Upadhayay', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_subheadline',
            field=models.TextField(default='Mastering enterprise infrastructure, Core Banking operations, SAP Business One, and Python/Django engineering — intertwined with evocative poetry and reflective literature.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_title',
            field=models.CharField(default='Systems Architect & Creative Thinker.', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.CharField(default='+977 9848485292', max_length=100),
        ),
    ]
