# Generated by Django 6.1 on 2026-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0006_siteconfiguration_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_demo_requestable',
            field=models.BooleanField(default=False, help_text="Enable 'Request a Demo' button for this project"),
        ),
    ]
