# Generated by Django 6.1 on 2026-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0007_project_is_demo_requestable'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your PDF CV/Resume', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='resume_url',
            field=models.URLField(blank=True, help_text='External URL to CV (e.g. Google Drive, Dropbox)'),
        ),
    ]
