# Generated by Django 6.1 on 2026-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0008_siteconfiguration_resume_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=60)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('path', models.CharField(db_index=True, default='/', max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('referrer_domain', models.CharField(blank=True, max_length=150)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(default='Desktop', max_length=30)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('visitor_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('visitor_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('visitor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_lead', models.BooleanField(db_index=True, default=False)),
                ('inquiry_intent', models.CharField(blank=True, max_length=200)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('visit_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='public_port_created_7df538_idx'), models.Index(fields=['is_lead', '-created_at'], name='public_port_is_lead_9dc614_idx'), models.Index(fields=['session_key'], name='public_port_session_28d91b_idx')],
            },
        ),
    ]
