# Generated by Django 6.1 on 2026-08-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_portal', '0009_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbiSAPComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200)),
                ('enterprise_value', models.TextField()),
                ('retail_value', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IbiSAPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Certified Nepal ERP • NRB & IRD CBMS Ready', max_length=200)),
                ('hero_title', models.CharField(default="The Intelligent ERP for Nepal's Regulated Enterprises", max_length=255)),
                ('hero_description', models.TextField(default='A high-performance, cost-effective alternative to SAP Business One. Built specifically for regulated Microfinance Institutions (MFIs), Cooperatives, Manufacturers, and Multi-Branch Retail Chains across Nepal.')),
                ('live_sandbox_url', models.URLField(default='https://ibisap.rajabhoj.com.np/login/?next=/')),
                ('live_sandbox_btn_text', models.CharField(default='Launch Live Cloud Sandbox', max_length=100)),
                ('metric_1_val', models.CharField(default='80%', max_length=50)),
                ('metric_1_lbl', models.CharField(default='Lower TCO vs SAP B1', max_length=150)),
                ('metric_2_val', models.CharField(default='100%', max_length=50)),
                ('metric_2_lbl', models.CharField(default='NRB IT Guidelines Compliant', max_length=150)),
                ('metric_3_val', models.CharField(default='v2.0', max_length=50)),
                ('metric_3_lbl', models.CharField(default='IRD CBMS Certified Sync', max_length=150)),
                ('metric_4_val', models.CharField(default='2081', max_length=50)),
                ('metric_4_lbl', models.CharField(default='Native Nepali Miti (Bikram Sambat)', max_length=150)),
                ('enterprise_title', models.CharField(default='Enterprise IbiSAP', max_length=150)),
                ('enterprise_tagline', models.CharField(default='Engineered for Institutions Requiring Strict Data Sovereignty', max_length=200)),
                ('enterprise_desc', models.TextField(default='Designed for regulated microfinance institutions (MFIs), cooperatives, hospitals, and large enterprises requiring NRB IT compliance, dedicated PostgreSQL/SQL HANA database servers, and maker-checker workflows.')),
                ('enterprise_features', models.TextField(default='On-Premises & Private Cloud Deployment: Complete data sovereignty on your physical hardware or dedicated private virtual cluster.\nNRB IT Security Guidelines Compliant: Granular RBAC, dual-authorization (maker-checker), automated DRP backups, and immutable audit logs.\nNative Nepali Miti (Bikram Sambat) Engine: Dual-calendar fiscal accounting (Shrawan 1 to Ashadh 31) with bi-directional AD/BS conversion.\nCertified IRD CBMS Real-Time Invoicing: Direct REST API synchronization with the Inland Revenue Department with offline failover queues.\nDedicated PostgreSQL / SQL HANA Instance: Pessimistic row-level locking guaranteeing ledger transaction consistency.')),
                ('retail_title', models.CharField(default='Retail IbiSAP SaaS', max_length=150)),
                ('retail_tagline', models.CharField(default='Zero DevOps Overhead for Retail Chains & Distributors', max_length=200)),
                ('retail_desc', models.TextField(default='Built for retail stores, supermarkets, pharmacies, and distributors who want enterprise-grade billing, inventory, and accounting with instant 60-second onboarding and zero hardware maintenance.')),
                ('retail_features', models.TextField(default='Isolated Multi-Tenant Architecture: Centralized application master with isolated schema/database segregation for every registered tenant.\nHigh-Speed Point of Sale (POS) & Barcode: Sub-second barcode scanning, thermal slip printing, loyalty discounts, and integrated Fonepay QR.\nMulti-Branch Inventory & Expiry Alerts: Real-time stock valuation across warehouses with batch-level expiry monitoring and automated reorders.\nZero DevOps Maintenance & Automated Backups: Continuous encrypted cloud snapshots, 99.9% availability, and automatic seamless version upgrades.\nInstant 60-Second Onboarding: Sign up and start generating invoices immediately on any browser, tablet, or POS terminal.')),
                ('cta_headline', models.CharField(default='Ready to Modernize Your Enterprise Infrastructure?', max_length=255)),
                ('cta_subheadline', models.TextField(default='Schedule a private 1-on-1 technical walkthrough, explore live modules, and calculate your migration savings vs legacy SAP systems.')),
            ],
            options={
                'verbose_name': 'IbiSAP ERP Configuration',
                'verbose_name_plural': 'IbiSAP ERP Configuration',
            },
        ),
        migrations.CreateModel(
            name='IbiSAPScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category_tag', models.CharField(default='Interface Showcase', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ibisap/screenshots/')),
                ('static_image_path', models.CharField(blank=True, default='gallery/ibisap-dashboard.png', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
