"""
Django settings for portfolio_site project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-key-do-not-use-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

raw_hosts = os.environ.get('ALLOWED_HOSTS', '*').split(',')
ALLOWED_HOSTS = list({h.strip() for h in raw_hosts if h.strip()} | {'localhost', '127.0.0.1', 'testserver', 'rajabhoj.com.np', 'www.rajabhoj.com.np'})

raw_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
CSRF_TRUSTED_ORIGINS = list({o.strip() for o in raw_origins if o.strip()} | {
    'https://rajabhoj.com.np',
    'https://www.rajabhoj.com.np',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
})



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'accounts',
    'public_portal',
    'private_portal',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'portfolio_site.middleware.PermissionsPolicyMiddleware',
    'public_portal.middleware.VisitorTelemetryMiddleware',
]


ROOT_URLCONF = 'portfolio_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'private_portal.context_processors.dashboard_settings',
                'private_portal.context_processors.admin_stats',
                'public_portal.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Use whitenoise for serving static files efficiently
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'private_portal:dashboard'
LOGOUT_REDIRECT_URL = 'public_portal:home'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Notification Configuration (Gmail SMTP & Lead Alerts)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').replace(' ', '').strip()
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'bhojrajupadhayay7@gmail.com')
NOTIFICATION_RECIPIENT_EMAIL = os.environ.get('NOTIFICATION_RECIPIENT_EMAIL', 'bhojrajupadhayay7@gmail.com')


# ==============================================================================
# Security & SSL Configuration (LiteSpeed Reverse Proxy & Production Hardening)
# ==============================================================================

# Required behind LiteSpeed / reverse proxy terminating SSL to detect HTTPS via header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS Redirection & HSTS (enforced in production when DEBUG=False)
if not DEBUG and os.environ.get('DISABLE_SSL_REDIRECT', 'False') != 'True':
    SECURE_SSL_REDIRECT = True

    # HTTP Strict Transport Security (HSTS - 2 years, subdomains, preload)
    SECURE_HSTS_SECONDS = 63072000          # 2 years
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Restrict session and CSRF cookies to HTTPS connections
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Cookie Hardening (applies to all environments)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Standard Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Content Security Policy (django-csp 4.0+)
# Starts in Report-Only mode to avoid breaking any scripts/styles.
# Set CSP_REPORT_ONLY=False in environment variables (.env) once verified to switch to enforcing.
CSP_REPORT_ONLY = os.environ.get('CSP_REPORT_ONLY', 'True') == 'True'

CSP_DIRECTIVES = {
    'default-src': ("'self'",),
    'style-src': ("'self'", "'unsafe-inline'", "fonts.googleapis.com", "cdnjs.cloudflare.com"),
    'font-src': ("'self'", "fonts.gstatic.com", "cdnjs.cloudflare.com"),
    'script-src': ("'self'", "cdnjs.cloudflare.com"),
    'img-src': ("'self'", "data:"),
}

if CSP_REPORT_ONLY:
    CONTENT_SECURITY_POLICY_REPORT_ONLY = {'DIRECTIVES': CSP_DIRECTIVES}
    CONTENT_SECURITY_POLICY = None
else:
    CONTENT_SECURITY_POLICY = {'DIRECTIVES': CSP_DIRECTIVES}
    CONTENT_SECURITY_POLICY_REPORT_ONLY = None


# Jazzmin Admin Theme Configuration
JAZZMIN_SETTINGS = {
    "site_title": "Sanctuary Admin",
    "site_header": "Sanctuary Control",
    "site_brand": "Sanctuary",
    "site_logo": None,
    "welcome_sign": "Welcome to the Sanctuary Command Center",
    "copyright": "Elite Guardian Sanctuary",
    "search_model": ["auth.User"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "To Portal", "url": "private_portal:dashboard", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "accounts", "private_portal"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "private_portal.Video": "fas fa-video",
        "private_portal.Photo": "fas fa-image",
        "private_portal.Message": "fas fa-envelope",
        "private_portal.Todo": "fas fa-tasks",
        "private_portal.Post": "fas fa-pen-fancy",
        "private_portal.Transaction": "fas fa-wallet",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-success",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
