# Generated by Django 6.0.2 on 2026-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Upload a custom background for the private dashboard.', null=True, upload_to='dashboard_bgs/')),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
