# Generated by Django 5.2.11 on 2026-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0002_dashboardsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='moviereview',
            options={'verbose_name_plural': 'Movie Reviews'},
        ),
    ]
