# Generated by Django 5.2.11 on 2026-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a custom profile picture.', null=True, upload_to='avatars/'),
        ),
    ]
