# Generated by Django 5.2.11 on 2026-04-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0016_alter_comment_options_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='MovieReview',
        ),
        migrations.DeleteModel(
            name='Novel',
        ),
    ]
