# Generated by Django 6.1 on 2026-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0017_remove_moviereview_user_remove_novel_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('poem', '✍️ Poem & Poetry'), ('tech', '💻 Tech & Engineering'), ('reflection', '🌿 Reflections & Life'), ('story', '📖 Story & Narrative'), ('thoughts', '💡 Thoughts & Ideas')], default='poem', max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief summary/snippet for cards and SEO'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin to featured section on Home & Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short subtitle or poetic hook', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags e.g. Poetry, Life, Nepali, Philosophy', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(help_text='Full post content or poem verses (newlines preserved)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible to public visitors'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
