# Generated by Django 6.1 on 2026-08-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0018_alter_blog_options_blog_category_blog_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-upload_timestamp', '-id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-upload_timestamp', '-id']},
        ),
    ]
