# Generated by Django 6.1 on 2026-09-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_portal', '0019_alter_photo_options_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
